name: "Build and Test .NET"

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      - name: Install dependencies
        run: |
          dotnet restore
          dotnet tool restore

      - name: Build Project
        run: dotnet build /warnAsError

      - name: Run Tests
        run: dotnet test
